/** Popular Indian retail and D2C brands. Specific names come before broader ones. */
export type IndiaRetailBrand = {
  canonicalName: string;
  aliases: string[];
  upiHandles: string[];
  senderDomains: string[];
  websiteDomain: string;
  logoFile: string;
  mark: string;
  color: string;
  categorySlug: string;
  /** Lowercase substrings used to recognise a payment. Longer, specific brands are listed first. */
  matchTokens: string[];
};

export const INDIA_RETAIL_BRANDS: IndiaRetailBrand[] = [
  {
    canonicalName: "Reliance Trends",
    aliases: ["Reliance Trends", "Trends Footwear"],
    upiHandles: ["reliancetrends", "trendsfootwear"],
    senderDomains: ["reliancetrends.com"],
    websiteDomain: "reliancetrends.com",
    logoFile: "reliance-trends.svg",
    mark: "RT",
    color: "#E31E24",
    categorySlug: "shopping",
    matchTokens: ["reliance trends", "reliancetrends", "trends footwear"],
  },
  {
    canonicalName: "Reliance Digital",
    aliases: ["Reliance Digital"],
    upiHandles: ["reliancedigital"],
    senderDomains: ["reliancedigital.in"],
    websiteDomain: "reliancedigital.in",
    logoFile: "reliance-digital.svg",
    mark: "RD",
    color: "#E31E24",
    categorySlug: "shopping",
    matchTokens: ["reliance digital", "reliancedigital"],
  },
  {
    canonicalName: "Ajio",
    aliases: ["Ajio", "Reliance Ajio"],
    upiHandles: ["ajio"],
    senderDomains: ["ajio.com"],
    websiteDomain: "ajio.com",
    logoFile: "ajio.svg",
    mark: "Ajio",
    color: "#2D2D2D",
    categorySlug: "shopping",
    matchTokens: ["ajio"],
  },
  {
    canonicalName: "JioMart",
    aliases: ["JioMart", "Jio Mart"],
    upiHandles: ["jiomart"],
    senderDomains: ["jiomart.com"],
    websiteDomain: "jiomart.com",
    logoFile: "jiomart.svg",
    mark: "JM",
    color: "#0A2885",
    categorySlug: "grocery",
    matchTokens: ["jiomart", "jio mart"],
  },
  {
    canonicalName: "Reliance Fresh",
    aliases: ["Reliance Fresh"],
    upiHandles: ["reliancefresh"],
    senderDomains: ["reliancefresh.com"],
    websiteDomain: "reliancefresh.com",
    logoFile: "reliance-fresh.svg",
    mark: "RF",
    color: "#0B7A3B",
    categorySlug: "grocery",
    matchTokens: ["reliance fresh", "reliancefresh"],
  },
  {
    canonicalName: "Smart Bazaar",
    aliases: ["Smart Bazaar", "Reliance Smart"],
    upiHandles: ["smartbazaar", "reliancesmart"],
    senderDomains: ["smartbazaar.relianceretail.com"],
    websiteDomain: "relianceretail.com",
    logoFile: "smart-bazaar.svg",
    mark: "SB",
    color: "#F5A300",
    categorySlug: "grocery",
    matchTokens: ["smart bazaar", "smartbazaar", "reliance smart"],
  },
  {
    canonicalName: "Nykaa",
    aliases: ["Nykaa", "Nykaa Fashion", "Nykaa Man", "FSN E-Commerce"],
    upiHandles: ["nykaa", "nykaafashion", "fsnecommerce"],
    senderDomains: ["nykaa.com"],
    websiteDomain: "nykaa.com",
    logoFile: "nykaa.svg",
    mark: "Nykaa",
    color: "#FC2779",
    categorySlug: "shopping",
    matchTokens: ["nykaa", "fsn e-commerce", "fsn ecommerce"],
  },
  {
    canonicalName: "Westside",
    aliases: ["Westside", "Trent Limited"],
    upiHandles: ["westside", "trentlimited"],
    senderDomains: ["westside.com"],
    websiteDomain: "westside.com",
    logoFile: "westside.svg",
    mark: "W",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["westside", "trent limited", "trent ltd"],
  },
  {
    canonicalName: "Pantaloons",
    aliases: ["Pantaloons", "Aditya Birla Fashion", "ABFRL"],
    upiHandles: ["pantaloons", "abfrl"],
    senderDomains: ["pantaloons.com"],
    websiteDomain: "pantaloons.com",
    logoFile: "pantaloons.svg",
    mark: "P",
    color: "#E10600",
    categorySlug: "shopping",
    matchTokens: ["pantaloons", "aditya birla fashion", "abfrl"],
  },
  {
    canonicalName: "Levi's",
    aliases: ["Levi's", "Levis", "Levi Strauss"],
    upiHandles: ["levis", "levistrauss"],
    senderDomains: ["levi.in", "levi.com"],
    websiteDomain: "levi.in",
    logoFile: "levis.svg",
    mark: "Levi's",
    color: "#C41230",
    categorySlug: "shopping",
    matchTokens: ["levi strauss", "levi's", "levis"],
  },
  {
    canonicalName: "Max Fashion",
    aliases: ["Max Fashion"],
    upiHandles: ["maxfashion"],
    senderDomains: ["maxfashion.com"],
    websiteDomain: "maxfashion.com",
    logoFile: "max-fashion.svg",
    mark: "Max",
    color: "#E4002B",
    categorySlug: "shopping",
    matchTokens: ["max fashion", "maxfashion"],
  },
  {
    canonicalName: "Lifestyle",
    aliases: ["Lifestyle", "Lifestyle Stores"],
    upiHandles: ["lifestylestores"],
    senderDomains: ["lifestylestores.com"],
    websiteDomain: "lifestylestores.com",
    logoFile: "lifestyle.svg",
    mark: "LS",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["lifestyle stores", "lifestylestores"],
  },
  {
    canonicalName: "Shoppers Stop",
    aliases: ["Shoppers Stop"],
    upiHandles: ["shoppersstop"],
    senderDomains: ["shoppersstop.com"],
    websiteDomain: "shoppersstop.com",
    logoFile: "shoppers-stop.svg",
    mark: "SS",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["shoppers stop", "shoppersstop"],
  },
  {
    canonicalName: "Zara",
    aliases: ["Zara"],
    upiHandles: ["zara"],
    senderDomains: ["zara.com"],
    websiteDomain: "zara.com",
    logoFile: "zara.svg",
    mark: "Zara",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["zara"],
  },
  {
    canonicalName: "H&M",
    aliases: ["H&M", "H and M", "Hennes"],
    upiHandles: ["handm", "hmhennes"],
    senderDomains: ["hm.com"],
    websiteDomain: "hm.com",
    logoFile: "hm.svg",
    mark: "H&M",
    color: "#E50010",
    categorySlug: "shopping",
    matchTokens: ["h&m", "h and m", "hennes"],
  },
  {
    canonicalName: "Decathlon",
    aliases: ["Decathlon"],
    upiHandles: ["decathlon"],
    senderDomains: ["decathlon.in"],
    websiteDomain: "decathlon.in",
    logoFile: "decathlon.svg",
    mark: "Dec",
    color: "#0082C3",
    categorySlug: "shopping",
    matchTokens: ["decathlon"],
  },
  {
    canonicalName: "Nike",
    aliases: ["Nike"],
    upiHandles: ["nike"],
    senderDomains: ["nike.com"],
    websiteDomain: "nike.com",
    logoFile: "nike.svg",
    mark: "Nike",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["nike"],
  },
  {
    canonicalName: "Adidas",
    aliases: ["Adidas"],
    upiHandles: ["adidas"],
    senderDomains: ["adidas.co.in"],
    websiteDomain: "adidas.co.in",
    logoFile: "adidas.svg",
    mark: "Adidas",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["adidas"],
  },
  {
    canonicalName: "Puma",
    aliases: ["Puma"],
    upiHandles: ["puma"],
    senderDomains: ["in.puma.com"],
    websiteDomain: "in.puma.com",
    logoFile: "puma.svg",
    mark: "Puma",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["puma"],
  },
  {
    canonicalName: "Bata",
    aliases: ["Bata"],
    upiHandles: ["bata"],
    senderDomains: ["bata.in"],
    websiteDomain: "bata.in",
    logoFile: "bata.svg",
    mark: "Bata",
    color: "#E31E24",
    categorySlug: "shopping",
    matchTokens: ["bata"],
  },
  {
    canonicalName: "Skechers",
    aliases: ["Skechers"],
    upiHandles: ["skechers"],
    senderDomains: ["skechers.in"],
    websiteDomain: "skechers.in",
    logoFile: "skechers.svg",
    mark: "Sk",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["skechers"],
  },
  {
    canonicalName: "Woodland",
    aliases: ["Woodland"],
    upiHandles: ["woodland"],
    senderDomains: ["woodlandworldwide.com"],
    websiteDomain: "woodlandworldwide.com",
    logoFile: "woodland.svg",
    mark: "WL",
    color: "#6B3E26",
    categorySlug: "shopping",
    matchTokens: ["woodland"],
  },
  {
    canonicalName: "Metro Shoes",
    aliases: ["Metro Shoes", "Mochi Shoes"],
    upiHandles: ["metroshoes", "mochishoes"],
    senderDomains: ["metroshoes.net"],
    websiteDomain: "metroshoes.net",
    logoFile: "metro-shoes.svg",
    mark: "Metro",
    color: "#1F4E79",
    categorySlug: "shopping",
    matchTokens: ["metro shoes", "metroshoes", "mochi shoes"],
  },
  {
    canonicalName: "Allen Solly",
    aliases: ["Allen Solly"],
    upiHandles: ["allensolly"],
    senderDomains: ["allensolly.com"],
    websiteDomain: "allensolly.com",
    logoFile: "allen-solly.svg",
    mark: "AS",
    color: "#1B3A4B",
    categorySlug: "shopping",
    matchTokens: ["allen solly", "allensolly"],
  },
  {
    canonicalName: "Peter England",
    aliases: ["Peter England"],
    upiHandles: ["peterengland"],
    senderDomains: ["peterengland.com"],
    websiteDomain: "peterengland.com",
    logoFile: "peter-england.svg",
    mark: "PE",
    color: "#8B1E3F",
    categorySlug: "shopping",
    matchTokens: ["peter england", "peterengland"],
  },
  {
    canonicalName: "Van Heusen",
    aliases: ["Van Heusen"],
    upiHandles: ["vanheusen"],
    senderDomains: ["vanheusenindia.com"],
    websiteDomain: "vanheusenindia.com",
    logoFile: "van-heusen.svg",
    mark: "VH",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["van heusen", "vanheusen"],
  },
  {
    canonicalName: "Louis Philippe",
    aliases: ["Louis Philippe"],
    upiHandles: ["louisphilippe"],
    senderDomains: ["louisphilippe.com"],
    websiteDomain: "louisphilippe.com",
    logoFile: "louis-philippe.svg",
    mark: "LP",
    color: "#1A1A1A",
    categorySlug: "shopping",
    matchTokens: ["louis philippe", "louisphilippe"],
  },
  {
    canonicalName: "Fabindia",
    aliases: ["Fabindia"],
    upiHandles: ["fabindia"],
    senderDomains: ["fabindia.com"],
    websiteDomain: "fabindia.com",
    logoFile: "fabindia.svg",
    mark: "Fab",
    color: "#8C2F39",
    categorySlug: "shopping",
    matchTokens: ["fabindia"],
  },
  {
    canonicalName: "Biba",
    aliases: ["Biba"],
    upiHandles: ["biba"],
    senderDomains: ["biba.in"],
    websiteDomain: "biba.in",
    logoFile: "biba.svg",
    mark: "Biba",
    color: "#C45C26",
    categorySlug: "shopping",
    matchTokens: ["biba"],
  },
  {
    canonicalName: "W for Woman",
    aliases: ["W for Woman", "WforWoman"],
    upiHandles: ["wforwoman"],
    senderDomains: ["wforwoman.com"],
    websiteDomain: "wforwoman.com",
    logoFile: "w-for-woman.svg",
    mark: "W",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["w for woman", "wforwoman"],
  },
  {
    canonicalName: "Myntra",
    aliases: ["Myntra", "Myntra Designs"],
    upiHandles: ["myntra"],
    senderDomains: ["myntra.com"],
    websiteDomain: "myntra.com",
    logoFile: "myntra.svg",
    mark: "Myntra",
    color: "#FF3F6C",
    categorySlug: "shopping",
    matchTokens: ["myntra"],
  },
  {
    canonicalName: "Meesho",
    aliases: ["Meesho", "Fashnear"],
    upiHandles: ["meesho", "fashnear"],
    senderDomains: ["meesho.com"],
    websiteDomain: "meesho.com",
    logoFile: "meesho.svg",
    mark: "Meesho",
    color: "#9B0066",
    categorySlug: "shopping",
    matchTokens: ["meesho", "fashnear"],
  },
  {
    canonicalName: "Tata CLiQ",
    aliases: ["Tata CLiQ", "Tata Cliq"],
    upiHandles: ["tatacliq"],
    senderDomains: ["tatacliq.com"],
    websiteDomain: "tatacliq.com",
    logoFile: "tata-cliq.svg",
    mark: "CLiQ",
    color: "#212121",
    categorySlug: "shopping",
    matchTokens: ["tata cliq", "tatacliq"],
  },
  {
    canonicalName: "Croma",
    aliases: ["Croma", "Infiniti Retail"],
    upiHandles: ["croma", "infinitiretail"],
    senderDomains: ["croma.com"],
    websiteDomain: "croma.com",
    logoFile: "croma.svg",
    mark: "Croma",
    color: "#12B886",
    categorySlug: "shopping",
    matchTokens: ["croma", "infiniti retail"],
  },
  {
    canonicalName: "Bewakoof",
    aliases: ["Bewakoof"],
    upiHandles: ["bewakoof"],
    senderDomains: ["bewakoof.com"],
    websiteDomain: "bewakoof.com",
    logoFile: "bewakoof.svg",
    mark: "B",
    color: "#F7E14C",
    categorySlug: "shopping",
    matchTokens: ["bewakoof"],
  },
  {
    canonicalName: "Snitch",
    aliases: ["Snitch"],
    upiHandles: ["snitch"],
    senderDomains: ["snitch.co.in"],
    websiteDomain: "snitch.co.in",
    logoFile: "snitch.svg",
    mark: "Snitch",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["snitch"],
  },
  {
    canonicalName: "The Souled Store",
    aliases: ["The Souled Store", "Souled Store"],
    upiHandles: ["thesouledstore", "souledstore"],
    senderDomains: ["thesouledstore.com"],
    websiteDomain: "thesouledstore.com",
    logoFile: "souled-store.svg",
    mark: "TSS",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["souled store", "thesouledstore", "souledstore"],
  },
  {
    canonicalName: "Uniqlo",
    aliases: ["Uniqlo"],
    upiHandles: ["uniqlo"],
    senderDomains: ["uniqlo.com"],
    websiteDomain: "uniqlo.com",
    logoFile: "uniqlo.svg",
    mark: "Uniqlo",
    color: "#E50012",
    categorySlug: "shopping",
    matchTokens: ["uniqlo"],
  },
  {
    canonicalName: "Marks & Spencer",
    aliases: ["Marks & Spencer", "Marks and Spencer", "M&S"],
    upiHandles: ["marksandspencer", "marksspencer"],
    senderDomains: ["marksandspencer.in"],
    websiteDomain: "marksandspencer.in",
    logoFile: "marks-spencer.svg",
    mark: "M&S",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["marks & spencer", "marks and spencer", "marksandspencer"],
  },
  {
    canonicalName: "Lenskart",
    aliases: ["Lenskart"],
    upiHandles: ["lenskart"],
    senderDomains: ["lenskart.com"],
    websiteDomain: "lenskart.com",
    logoFile: "lenskart.svg",
    mark: "LK",
    color: "#00BAC6",
    categorySlug: "shopping",
    matchTokens: ["lenskart"],
  },
  {
    canonicalName: "Titan",
    aliases: ["Titan", "Titan Eyeplus"],
    upiHandles: ["titan", "titaneyeplus"],
    senderDomains: ["titan.co.in"],
    websiteDomain: "titan.co.in",
    logoFile: "titan.svg",
    mark: "Titan",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["titan eyeplus", "titaneyeplus", "titan"],
  },
  {
    canonicalName: "Tanishq",
    aliases: ["Tanishq"],
    upiHandles: ["tanishq"],
    senderDomains: ["tanishq.co.in"],
    websiteDomain: "tanishq.co.in",
    logoFile: "tanishq.svg",
    mark: "Tanishq",
    color: "#8A6A2F",
    categorySlug: "shopping",
    matchTokens: ["tanishq"],
  },
  {
    canonicalName: "boAt",
    aliases: ["boAt", "boAt Lifestyle", "Imagine Marketing"],
    upiHandles: ["boatlifestyle", "imaginemarketing"],
    senderDomains: ["boat-lifestyle.com"],
    websiteDomain: "boat-lifestyle.com",
    logoFile: "boat.svg",
    mark: "boAt",
    color: "#111111",
    categorySlug: "shopping",
    matchTokens: ["boat lifestyle", "boatlifestyle", "imagine marketing"],
  },
  {
    canonicalName: "Mamaearth",
    aliases: ["Mamaearth", "Honasa"],
    upiHandles: ["mamaearth", "honasa"],
    senderDomains: ["mamaearth.in"],
    websiteDomain: "mamaearth.in",
    logoFile: "mamaearth.svg",
    mark: "Mama",
    color: "#6FBF4A",
    categorySlug: "personal",
    matchTokens: ["mamaearth", "honasa"],
  },
  {
    canonicalName: "Sugar Cosmetics",
    aliases: ["Sugar Cosmetics", "SUGAR"],
    upiHandles: ["sugarcosmetics"],
    senderDomains: ["sugarcosmetics.com"],
    websiteDomain: "sugarcosmetics.com",
    logoFile: "sugar-cosmetics.svg",
    mark: "Sugar",
    color: "#111111",
    categorySlug: "personal",
    matchTokens: ["sugar cosmetics", "sugarcosmetics"],
  },
  {
    canonicalName: "Purplle",
    aliases: ["Purplle"],
    upiHandles: ["purplle"],
    senderDomains: ["purplle.com"],
    websiteDomain: "purplle.com",
    logoFile: "purplle.svg",
    mark: "Purplle",
    color: "#7B2D8E",
    categorySlug: "personal",
    matchTokens: ["purplle"],
  },
  {
    canonicalName: "FirstCry",
    aliases: ["FirstCry", "First Cry"],
    upiHandles: ["firstcry"],
    senderDomains: ["firstcry.com"],
    websiteDomain: "firstcry.com",
    logoFile: "firstcry.svg",
    mark: "FC",
    color: "#F15A22",
    categorySlug: "shopping",
    matchTokens: ["firstcry", "first cry"],
  },
  {
    canonicalName: "DMart",
    aliases: ["DMart", "D-Mart", "Avenue Supermarts"],
    upiHandles: ["dmart", "avenuesupermarts"],
    senderDomains: ["dmart.in"],
    websiteDomain: "dmart.in",
    logoFile: "dmart.svg",
    mark: "DMart",
    color: "#007A33",
    categorySlug: "grocery",
    matchTokens: ["avenue supermarts", "d-mart", "dmart"],
  },
  {
    canonicalName: "BigBasket",
    aliases: ["BigBasket", "Big Basket"],
    upiHandles: ["bigbasket"],
    senderDomains: ["bigbasket.com"],
    websiteDomain: "bigbasket.com",
    logoFile: "bigbasket.svg",
    mark: "bb",
    color: "#84C225",
    categorySlug: "grocery",
    matchTokens: ["bigbasket", "big basket"],
  },
  {
    canonicalName: "IKEA",
    aliases: ["IKEA"],
    upiHandles: ["ikea"],
    senderDomains: ["ikea.com"],
    websiteDomain: "ikea.com",
    logoFile: "ikea.svg",
    mark: "IKEA",
    color: "#0058A3",
    categorySlug: "household",
    matchTokens: ["ikea"],
  },
  {
    canonicalName: "Wakefit",
    aliases: ["Wakefit"],
    upiHandles: ["wakefit"],
    senderDomains: ["wakefit.co"],
    websiteDomain: "wakefit.co",
    logoFile: "wakefit.svg",
    mark: "WF",
    color: "#5B2C6F",
    categorySlug: "household",
    matchTokens: ["wakefit"],
  },
  {
    canonicalName: "Urban Company",
    aliases: ["Urban Company", "UrbanClap"],
    upiHandles: ["urbancompany", "urbanclap"],
    senderDomains: ["urbancompany.com"],
    websiteDomain: "urbancompany.com",
    logoFile: "urban-company.svg",
    mark: "UC",
    color: "#6E42E5",
    categorySlug: "personal",
    matchTokens: ["urban company", "urbancompany", "urbanclap"],
  },
  {
    canonicalName: "PharmEasy",
    aliases: ["PharmEasy"],
    upiHandles: ["pharmeasy"],
    senderDomains: ["pharmeasy.in"],
    websiteDomain: "pharmeasy.in",
    logoFile: "pharmeasy.svg",
    mark: "PE",
    color: "#10847E",
    categorySlug: "pharmacy",
    matchTokens: ["pharmeasy"],
  },
  {
    canonicalName: "Netmeds",
    aliases: ["Netmeds"],
    upiHandles: ["netmeds"],
    senderDomains: ["netmeds.com"],
    websiteDomain: "netmeds.com",
    logoFile: "netmeds.svg",
    mark: "NM",
    color: "#1A4F8B",
    categorySlug: "pharmacy",
    matchTokens: ["netmeds"],
  },
  {
    canonicalName: "Tata 1mg",
    aliases: ["Tata 1mg", "1mg"],
    upiHandles: ["onemg", "1mg"],
    senderDomains: ["1mg.com"],
    websiteDomain: "1mg.com",
    logoFile: "tata-1mg.svg",
    mark: "1mg",
    color: "#FF6F61",
    categorySlug: "pharmacy",
    matchTokens: ["tata 1mg", "1mg", "onemg"],
  },
  {
    canonicalName: "Cult.fit",
    aliases: ["Cult.fit", "Cultfit", "Cure.fit"],
    upiHandles: ["cultfit", "curefit"],
    senderDomains: ["cult.fit"],
    websiteDomain: "cult.fit",
    logoFile: "cultfit.svg",
    mark: "Cult",
    color: "#111111",
    categorySlug: "sports",
    matchTokens: ["cult.fit", "cultfit", "cure.fit", "curefit"],
  },
  {
    canonicalName: "Starbucks",
    aliases: ["Starbucks", "Tata Starbucks"],
    upiHandles: ["starbucks", "tatastarbucks"],
    senderDomains: ["starbucks.in"],
    websiteDomain: "starbucks.in",
    logoFile: "starbucks.svg",
    mark: "Sbux",
    color: "#00704A",
    categorySlug: "food",
    matchTokens: ["tata starbucks", "starbucks"],
  },
  {
    canonicalName: "McDonald's",
    aliases: ["McDonald's", "McDonalds"],
    upiHandles: ["mcdonalds"],
    senderDomains: ["mcdonaldsindia.com"],
    websiteDomain: "mcdonaldsindia.com",
    logoFile: "mcdonalds.svg",
    mark: "McD",
    color: "#DA291C",
    categorySlug: "food",
    matchTokens: ["mcdonald's", "mcdonalds"],
  },
  {
    canonicalName: "KFC",
    aliases: ["KFC", "Kentucky Fried Chicken"],
    upiHandles: ["kfc"],
    senderDomains: ["kfc.co.in"],
    websiteDomain: "online.kfc.co.in",
    logoFile: "kfc.svg",
    mark: "KFC",
    color: "#E4002B",
    categorySlug: "food",
    matchTokens: ["kentucky fried chicken", "kfc"],
  },
  {
    canonicalName: "Burger King",
    aliases: ["Burger King"],
    upiHandles: ["burgerking"],
    senderDomains: ["burgerking.in"],
    websiteDomain: "burgerking.in",
    logoFile: "burger-king.svg",
    mark: "BK",
    color: "#D62300",
    categorySlug: "food",
    matchTokens: ["burger king", "burgerking"],
  },
  {
    canonicalName: "Chaayos",
    aliases: ["Chaayos"],
    upiHandles: ["chaayos"],
    senderDomains: ["chaayos.com"],
    websiteDomain: "chaayos.com",
    logoFile: "chaayos.svg",
    mark: "Chai",
    color: "#6B3E26",
    categorySlug: "food",
    matchTokens: ["chaayos"],
  },
  {
    canonicalName: "Reliance Retail",
    aliases: ["Reliance Retail", "Reliance Retail Ventures", "RRVL"],
    upiHandles: ["relianceretail", "rrvl"],
    senderDomains: ["relianceretail.com"],
    websiteDomain: "relianceretail.com",
    logoFile: "reliance-retail.svg",
    mark: "RR",
    color: "#004B8D",
    categorySlug: "shopping",
    matchTokens: ["reliance retail", "relianceretail", "rrvl"],
  },
];
