import { getStore } from "../db/index.js";
import type { NewTransactionInput } from "../db/types.js";

const DEMO_TRANSACTIONS: NewTransactionInput[] = [
  {
    date: "2026-10-01",
    amount: 450,
    merchant: "Swiggy",
    description: "Swiggy",
    category: "food",
    type: "debit",
  },
  {
    date: "2026-10-01",
    amount: 1200,
    merchant: "Amazon",
    description: "Amazon",
    category: "shopping",
    type: "debit",
  },
  {
    date: "2026-10-02",
    amount: 350,
    merchant: "Starbucks",
    description: "Starbucks",
    category: "coffee",
    type: "debit",
  },
  {
    date: "2026-10-02",
    amount: 5000,
    merchant: "Salary Credit",
    description: "Salary Credit",
    category: "passed-on",
    type: "credit",
  },
  {
    date: "2026-10-03",
    amount: 2500,
    merchant: "Zerodha",
    description: "Zerodha",
    category: "investments",
    type: "debit",
  },
  {
    date: "2026-10-03",
    amount: 280,
    merchant: "Uber",
    description: "Uber",
    category: "travel",
    type: "debit",
  },
  {
    date: "2026-10-04",
    amount: 150,
    merchant: "Dunkin",
    description: "Dunkin",
    category: "coffee",
    type: "debit",
  },
  {
    date: "2026-10-04",
    amount: 800,
    merchant: "Gym",
    description: "Gym",
    category: "health",
    type: "debit",
  },
  {
    date: "2026-10-05",
    amount: 1500,
    merchant: "Rent",
    description: "Rent",
    category: "rent",
    type: "debit",
  },
  {
    date: "2026-10-05",
    amount: 600,
    merchant: "Zomato",
    description: "Zomato",
    category: "food",
    type: "debit",
  },
  {
    date: "2026-10-06",
    amount: 400,
    merchant: "Book Store",
    description: "Book Store",
    category: "books",
    type: "debit",
  },
  {
    date: "2026-10-06",
    amount: 250,
    merchant: "Gas",
    description: "Gas",
    category: "utilities",
    type: "debit",
  },
  {
    date: "2026-10-07",
    amount: 3000,
    merchant: "Bata",
    description: "Bata",
    category: "shopping",
    type: "debit",
  },
  {
    date: "2026-10-07",
    amount: 500,
    merchant: "Netflix",
    description: "Netflix",
    category: "entertainment",
    type: "debit",
  },
  {
    date: "2026-10-08",
    amount: 1200,
    merchant: "Flipkart",
    description: "Flipkart",
    category: "shopping",
    type: "debit",
  },
  {
    date: "2026-10-08",
    amount: 100,
    merchant: "Chai",
    description: "Chai",
    category: "food",
    type: "debit",
  },
  {
    date: "2026-10-09",
    amount: 800,
    merchant: "Myntra",
    description: "Myntra",
    category: "shopping",
    type: "debit",
  },
  {
    date: "2026-10-09",
    amount: 300,
    merchant: "Petrol",
    description: "Petrol",
    category: "travel",
    type: "debit",
  },
  {
    date: "2026-10-10",
    amount: 2000,
    merchant: "Broiler Chicken",
    description: "Broiler Chicken",
    category: "groceries",
    type: "debit",
  },
];

export async function loadDemoData(userId: string): Promise<{ created: number }> {
  const store = await getStore();
  const result = await store.insertTransactions(userId, DEMO_TRANSACTIONS);
  return { created: result.inserted };
}
