import { getStore } from "../db/index.js";
import type { NewTransactionInput } from "../db/types.js";

const DEMO_TRANSACTIONS: NewTransactionInput[] = [
  {
    importId: null,
    accountId: null,
    date: "2026-10-01",
    time: null,
    amount: 450,
    merchant: "Swiggy",
    description: "Swiggy Food Delivery",
    type: "debit",
    upiId: "swiggy@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-01",
    time: null,
    amount: 1200,
    merchant: "Amazon",
    description: "Amazon Online Shopping",
    type: "debit",
    upiId: "amazon@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-02",
    time: null,
    amount: 350,
    merchant: "Starbucks",
    description: "Starbucks Coffee",
    type: "debit",
    upiId: "starbucks@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-02",
    time: null,
    amount: 5000,
    merchant: null,
    description: "Salary Credit",
    type: "credit",
    upiId: null,
    payee: "Employer",
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-03",
    time: null,
    amount: 2500,
    merchant: "Zerodha",
    description: "Investment in Stocks",
    type: "debit",
    upiId: "zerodha@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-03",
    time: null,
    amount: 280,
    merchant: "Uber",
    description: "Uber Ride",
    type: "debit",
    upiId: "uber@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-04",
    time: null,
    amount: 150,
    merchant: "Dunkin",
    description: "Dunkin Coffee & Donuts",
    type: "debit",
    upiId: "dunkin@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-04",
    time: null,
    amount: 800,
    merchant: "Gold Gym",
    description: "Gym Membership",
    type: "debit",
    upiId: "gym@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-05",
    time: null,
    amount: 1500,
    merchant: null,
    description: "Rent Payment",
    type: "debit",
    upiId: null,
    payee: "Landlord",
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-05",
    time: null,
    amount: 600,
    merchant: "Zomato",
    description: "Zomato Food Delivery",
    type: "debit",
    upiId: "zomato@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-06",
    time: null,
    amount: 400,
    merchant: "Crossword Bookstore",
    description: "Books Purchase",
    type: "debit",
    upiId: "crossword@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-06",
    time: null,
    amount: 250,
    merchant: null,
    description: "Electricity Bill",
    type: "debit",
    upiId: null,
    payee: "Power Company",
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-07",
    time: null,
    amount: 3000,
    merchant: "Bata",
    description: "Shoes and Footwear",
    type: "debit",
    upiId: "bata@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-07",
    time: null,
    amount: 500,
    merchant: "Netflix",
    description: "Netflix Subscription",
    type: "debit",
    upiId: "netflix@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-08",
    time: null,
    amount: 1200,
    merchant: "Flipkart",
    description: "Electronics Purchase",
    type: "debit",
    upiId: "flipkart@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-08",
    time: null,
    amount: 100,
    merchant: "Tea Stall",
    description: "Tea",
    type: "debit",
    upiId: "tea@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-09",
    time: null,
    amount: 800,
    merchant: "Myntra",
    description: "Clothing Purchase",
    type: "debit",
    upiId: "myntra@upi",
    payee: null,
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-09",
    time: null,
    amount: 300,
    merchant: null,
    description: "Petrol Pump",
    type: "debit",
    upiId: null,
    payee: "Petrol Station",
  },
  {
    importId: null,
    accountId: null,
    date: "2026-10-10",
    time: null,
    amount: 2000,
    merchant: "Nature's Basket",
    description: "Groceries",
    type: "debit",
    upiId: "groceries@upi",
    payee: null,
  },
];

export async function loadDemoData(userId: string): Promise<{ created: number }> {
  const store = await getStore();
  const result = await store.insertTransactions(userId, DEMO_TRANSACTIONS);
  return { created: result.inserted };
}
