/** Keep in sync with backend `enums/category`. */
export const CategorySlug = {
  Food: "food",
  Shopping: "shopping",
  Travel: "travel",
  ScootyRental: "scooty-rental",
  Healthcare: "healthcare",
  Family: "family",
  Furniture: "furniture",
  CookMaid: "cook-maid",
  Household: "household",
  Rent: "rent",
  Brokerage: "brokerage",
  Outing: "outing",
  Dinner: "dinner",
  Sports: "sports",
  FunActivity: "fun-activity",
  Investments: "investments",
  Vices: "vices",
  Booze: "booze",
  Cigarettes: "cigarettes",
  Banks: "banks",
  Personal: "personal",
  RandomExpense: "random-expense",
  Salary: "salary",
  FromHome: "from-home",
  Other: "other",
} as const;

export type CategorySlug = (typeof CategorySlug)[keyof typeof CategorySlug];
