export const CATEGORY_SLUGS = [
  "food",
  "shopping",
  "travel",
  "scooty-rental",
  "healthcare",
  "family",
  "household",
  "rent",
  "brokerage",
  "outing",
  "dinner",
  "sports",
  "fun-activity",
  "investments",
  "vices",
  "booze",
  "cigarettes",
  "banks",
  "personal",
  "random-expense",
  "salary",
  "from-home",
  "other",
] as const;

export const CategorySlug = {
  Food: "food",
  Shopping: "shopping",
  Travel: "travel",
  ScootyRental: "scooty-rental",
  Healthcare: "healthcare",
  Family: "family",
  Household: "household",
  Rent: "rent",
  Brokerage: "brokerage",
  Outing: "outing",
  Dinner: "dinner",
  Sports: "sports",
  FunActivity: "fun-activity",
  Investments: "investments",
  Vices: "vices",
  Booze: "booze",
  Cigarettes: "cigarettes",
  Banks: "banks",
  Personal: "personal",
  RandomExpense: "random-expense",
  Salary: "salary",
  FromHome: "from-home",
  Other: "other",
} as const;

export type CategorySlug = (typeof CATEGORY_SLUGS)[number];
